### PR TITLE
- support channels in replicator configurator

### PR DESCRIPTION
**Pull request by tediyuwono**
-  support channels in replicator configurator
- update to couchbase lite 2.7.0

### CODE REVIEW

**Comment by bawelter** [comment]
I will make sure to include this in the next release. Thank you for coming up with the solution!

**Review by bawelter — COMMENTED** [review]
This looks good I will just need to do the iOS part and review it a bit more.  Thank you for the contribution!

**Comment by allanwolski** [comment]
I need this too.

Do you know when it will be available?

**Comment by bawelter** [comment]
This doesn't currently have the iOS integration

**Pull request merged**
