### PR TITLE
Add setting logging level feature

### PR DESCRIPTION
**Pull request by ethras**
Hi,

This is just a quick PR to allow setting the logging level. 
It was set on debug by default without allowing us to change it which can be annoying sometimes.

This is one of if not my first PR so let me know if I did something wrong ;)

### CODE REVIEW

**Comment by bawelter** [comment]
Just need some details on the changes to the pod files and will also need to bump the build number for this to publish to the null safety pre-release version.

**Comment by ethras** [comment]
About the pod files, when I cloned your project, I ran
`cd hello/example; flutter build ios --no-codesign` as explained [here](https://github.com/SaltechSystems/couchbase_lite/pull/94) (Step 2c: Add iOS platform code (.swift/.h+.m)) which failed and I asked me to remove the current ios/Podfile. It then recreated a new one. 
Finally I just ran  `pod update` then `flutter build ios --no-codesign`.

**Comment by bawelter** [comment]
Just need a version bump and we can merge.  So once you commit that and I merge it’ll allow the cd pipeline to publish the this change.

**Comment by bawelter** [comment]
Change `version: 3.0.0-nullsafety.0` in `pub spec.yaml`

**Pull request merged**
