### PR TITLE
Fix Blob content tpye not parsed correctly

### PR DESCRIPTION
**Pull request by Rudiksz**
Added getBlob method to query result

### CODE REVIEW

**Comment by bawelter** [comment]
The content type was correct before the issue is in the platform code.  Your code gives you the desired outcome because the contentType key is not found so it goes to the else clause on the platform code when contentType is missing.

**Comment by Rudiksz** [comment]
That's confusing, because Couchbase uses "content_type" internally and the platform code also returns "content_type". Initially i just changed the fromMap method, but then I just assumed the toMap should be like that to.
Apparently I was wrong and the blobs are getting deleted again.  So as it is now the platform code sends "content_type" but expects "contentType", at least on Android.

As I don't have a way to test on ios I prefer not touching any of the platform code.

**Comment by Rudiksz** [comment]
I fixed the toMap method for now, and it works even if it's a bit ugly.

But come to think of it, seems like there's something wrong with the platform code's else clause too, because altough it supposed to set the original value if content type is null, the blobs get deleted instead anyway.

**Comment by bawelter** [comment]
Well if you get the android code tested I can verify the iOS before we push it live.

**Comment by Rudiksz** [comment]
It works as it is now, but having "content_type" in fromMap and "contentType" in toMap smells. The fix is somewhere in the platform code but I don't have time to dig in to that.  It's good enough for what I need.

**Comment by bawelter** [comment]
I'm not going to merge this because it won't actually fix the issue, this will actually just remove the ability to add or update Blobs.  Looked at the code and my guess is that the actual issue is that the Blob isn't being processed by the platform code.  If you are getting "content_type" then this is directly from the CouchbaseLite Blob object and needs to be processed.  Below are the methods used to generate the Map and as you can see the Blob will not get processed if it is not a root property so my guess is that the Blob is not a root property and this is causing the issue.  To fix the issue the platform code needs changed updated to recurse over the map or a Serializer needs written to process everything properly.

```
  Map<String, Object> getDocumentWithId(Database database, String _id) {
        HashMap<String, Object> resultMap = new HashMap<>();

        Document document = database.getDocument(_id);
        if (document != null) {
            resultMap.put("doc", getJSONMap(document.toMap()));
            resultMap.put("id", document.getId());
            resultMap.put("sequence", document.getSequence());
        } else {
            resultMap.put("doc", null);
            resultMap.put("id", _id);
        }

        return resultMap;
    }

  private Map<String, Object> getJSONMap(Map<String, Object> _map) {
        HashMap<String,Object> parsed = new HashMap<>();
        for (Map.Entry<String,Object> entry: _map.entrySet()) {
            Object value = entry.getValue();
            if (value instanceof Blob) {
                Blob blob = (Blob) value;
                HashMap<String,Object> json = new HashMap<>();
                json.put("contentType", blob.getContentType());
                json.put("digest", blob.digest());
                json.put("length", blob.length());
                json.put("@type","blob");
                parsed.put(entry.getKey(),json);
            } else {
                parsed.put(entry.getKey(),entry.getValue());
            }
        }

        return parsed;
    }
```

**Comment by bawelter** [comment]
Just to clarify this could break working production code for other users.  That is why I am not accepting this change as is.

**Comment by Rudiksz** [comment]
`I'm not going to merge this because it won't actually fix the issue, this will actually just remove the ability to add or update Blobs.
`
I don't get it, how can this fix break something that is already broken to the point of being useless? Without this fix Blobs are getting deleted when saving documents.


Of course the document is not a root property. I'm doing a select.all in a query, the results are returned in map with the key as the name of the database (or alias).
Like this
```
[
    {
        "travel-sample": {
            "callsign": "MILE-AIR",
            "country": "United States",
            "iata": "Q5",
            "icao": "MLA",
            "id": 10,
            "name": "40-Mile Air",
            "type": "airline"
        }
    },
]
```

That's why I had to add the Result.fromMap method to be able to reach the actual document. My guess is that nobody is doing any queries like this, because it was literally the first issue I bumped into when using the library. I'm also not using the Document and MutableDocument classes, because I have my own data classes that do json serialization which works fine with the json maps returned from the native code (except the blobs).


If the getJSONMap method returns "content_type" (as it should), the dart code would be consitent regardless of where the blob fragment is in the result,  and it still would not impact any production code.

**Comment by Rudiksz** [comment]
I mean, I get it that it break the blobs coming from the "getDocument" method, but my point was that the platform code shouldn't rewrite the json map key in the getJSONMap method, because it breaks the contract.

Returning "content_type" and fixing the Blob.fromMap method fixes both cases (document results and query results) without any impact on dart code, I think. It's an internal detail to the library. I still use dart's Blob class and its "contentType" field.

If there's no desire to change the platform code, the Blob._fromMap should at least be able to handle both cases.

Maybe this would be good enough and backwards compatible.
`this._contentType = map["contentType"] ?? map["content_type"];`

**Comment by bawelter** [comment]
> I mean, I get it that it break the blobs coming from the "getDocument" method, but my point was that the platform code shouldn't rewrite the json map key in the getJSONMap method, because it breaks the contract.
> 
> Returning "content_type" and fixing the Blob.fromMap method fixes both cases (document results and query results) without any impact on dart code, I think. It's an internal detail to the library. I still use dart's Blob class and its "contentType" field.
> 
> If there's no desire to change the platform code, the Blob._fromMap should at least be able to handle both cases.
> 
> Maybe this would be good enough and backwards compatible.
> `this._contentType = map["contentType"] ?? map["content_type"];`

Have you tested saving a new Blob with this code?  Please feel free to change the "contentType" to "content_type" on the platform code if you believe this will fix the issue and as long as this is the only thing changed it shouldn't cause any issues.

**Comment by bawelter** [comment]
> `I'm not going to merge this because it won't actually fix the issue, this will actually just remove the ability to add or update Blobs. `
> I don't get it, how can this fix break something that is already broken to the point of being useless? Without this fix Blobs are getting deleted when saving documents.
> 
> Of course the document is not a root property. I'm doing a select.all in a query, the results are returned in map with the key as the name of the database (or alias).
> Like this
> 
> ```
> [
>     {
>         "travel-sample": {
>             "callsign": "MILE-AIR",
>             "country": "United States",
>             "iata": "Q5",
>             "icao": "MLA",
>             "id": 10,
>             "name": "40-Mile Air",
>             "type": "airline"
>         }
>     },
> ]
> ```
> 
> That's why I had to add the Result.fromMap method to be able to reach the actual document. My guess is that nobody is doing any queries like this, because it was literally the first issue I bumped into when using the library. I'm also not using the Document and MutableDocument classes, because I have my own data classes that do json serialization which works fine with the json maps returned from the native code (except the blobs).
> 
> If the getJSONMap method returns "content_type" (as it should), the dart code would be consitent regardless of where the blob fragment is in the result, and it still would not impact any production code.

Blobs are not supported in Queries and have not been tested with them.  If you would like to fix this and do a pull request I would be happy to merge the code as long as it has been tested.  I just can't merge code which will break existing code.  I can look into this more in the future and will help answer any questions but I don't have the time to fix this issue right now.

**Comment by Rudiksz** [comment]
> > I mean, I get it that it break the blobs coming from the "getDocument" method, but my point was that the platform code shouldn't rewrite the json map key in the getJSONMap method, because it breaks the contract.
> > Returning "content_type" and fixing the Blob.fromMap method fixes both cases (document results and query results) without any impact on dart code, I think. It's an internal detail to the library. I still use dart's Blob class and its "contentType" field.
> > If there's no desire to change the platform code, the Blob._fromMap should at least be able to handle both cases.
> > Maybe this would be good enough and backwards compatible.
> > `this._contentType = map["contentType"] ?? map["content_type"];`
> 
> Have you tested saving a new Blob with this code? Please feel free to change the "contentType" to "content_type" on the platform code if you believe this will fix the issue and as long as this is the only thing changed it shouldn't cause any issues.

It was just a suggestion for a fix that would impact only the dart code, and only that line to fix the issue I have while keeping the existing code unaffected. 

To be clear, reading the blobs from the queries worked even before and writing them to the database worked when I was doing the initial save (because I would set the content type based on the selected image).

The issue was reading it back from the database (say after I restarted the app) the dart class would not read properly the content type. Everything else was there and I was able to read the blob content and all, but saving the document to the database would delete the blob altoghether, for whatever reason. Making sure dart code read the content type properly fixed the issue.

I'll look into fixing it in the platform code, as I believe it would be cleaner and still backwards compatible.

**Comment by bawelter** [comment]
> > > I mean, I get it that it break the blobs coming from the "getDocument" method, but my point was that the platform code shouldn't rewrite the json map key in the getJSONMap method, because it breaks the contract.
> > > Returning "content_type" and fixing the Blob.fromMap method fixes both cases (document results and query results) without any impact on dart code, I think. It's an internal detail to the library. I still use dart's Blob class and its "contentType" field.
> > > If there's no desire to change the platform code, the Blob._fromMap should at least be able to handle both cases.
> > > Maybe this would be good enough and backwards compatible.
> > > `this._contentType = map["contentType"] ?? map["content_type"];`
> > 
> > 
> > Have you tested saving a new Blob with this code? Please feel free to change the "contentType" to "content_type" on the platform code if you believe this will fix the issue and as long as this is the only thing changed it shouldn't cause any issues.
> 
> It was just a suggestion for a fix that would impact only the dart code, and only that line to fix the issue I have while keeping the existing code unaffected.
> 
> To be clear, reading the blobs from the queries worked even before and writing them to the database worked when I was doing the initial save (because I would set the content type based on the selected image).
> 
> The issue was reading it back from the database (say after I restarted the app) the dart class would not read properly the content type. Everything else was there and I was able to read the blob content and all, but saving the document to the database would delete the blob altoghether, for whatever reason. Making sure dart code read the content type properly fixed the issue.
> 
> I'll look into fixing it in the platform code, as I believe it would be cleaner and still backwards compatible.

It should definitely be done this way.  It has been over a year since I worked on blobs so it's coming back to me why I did everything the way I did.  As for the contentType part I believe that is just because it needs to be processed by our code before being passed through the platform channel because of the data.  The file from the blob I was concerned would cause issues because on the native code it lazy loads the file to prevent issues.  The other major thing is that in order to properly delete the blob you should never just delete the property but instead you need to delete the data in the blob and pass it as an update.  If you don't do this then the file will remain in the database and I don't think it would delete off the phone either.  There are just a lot of things with Blobs that need handled differently and special attention.  So we would need to write the deletion of the Blob differently and possibly adding a flag to make it more of an intentional action.  Depends on what support we want to provide with Blobs.

**Comment by bawelter** [comment]
> > > I mean, I get it that it break the blobs coming from the "getDocument" method, but my point was that the platform code shouldn't rewrite the json map key in the getJSONMap method, because it breaks the contract.
> > > Returning "content_type" and fixing the Blob.fromMap method fixes both cases (document results and query results) without any impact on dart code, I think. It's an internal detail to the library. I still use dart's Blob class and its "contentType" field.
> > > If there's no desire to change the platform code, the Blob._fromMap should at least be able to handle both cases.
> > > Maybe this would be good enough and backwards compatible.
> > > `this._contentType = map["contentType"] ?? map["content_type"];`
> > 
> > 
> > Have you tested saving a new Blob with this code? Please feel free to change the "contentType" to "content_type" on the platform code if you believe this will fix the issue and as long as this is the only thing changed it shouldn't cause any issues.
> 
> It was just a suggestion for a fix that would impact only the dart code, and only that line to fix the issue I have while keeping the existing code unaffected.
> 
> To be clear, reading the blobs from the queries worked even before and writing them to the database worked when I was doing the initial save (because I would set the content type based on the selected image).
> 
> The issue was reading it back from the database (say after I restarted the app) the dart class would not read properly the content type. Everything else was there and I was able to read the blob content and all, but saving the document to the database would delete the blob altoghether, for whatever reason. Making sure dart code read the content type properly fixed the issue.
> 
> I'll look into fixing it in the platform code, as I believe it would be cleaner and still backwards compatible.

I also wanted you to be aware that saving documents without using the document(withID) method will result in a document conflict every time a document is saved if it already exists and will transmit the most data possible since it will be considered a new document on every update.  You will also want to check and make sure the attachments are properly deleted with the overwrite as a new document or you will have a duplicated attachment for the Blob every time you save the document which could add up pretty quickly.

**Comment by Rudiksz** [comment]
That's very confusing and counterintuitive. I already have to keep an extra copy of the id in my documents to be able to do a proper query, now I have to keep track of the revision and sequence manually too?

Having to do an extra read for **every** document I want to save, just to get the sequence number is a very bad design choice, and having queries that don't return id and revision are almost useless then.

Also I don't know if it's relevant or intended but the plugin code does not return the document revision even when doing a getDocument call. I was under the impression that updating a document requires an ID and the revision number.


`You will also want to check and make sure the attachments are properly deleted with the overwrite as a new document or you will have a duplicated attachment for the Blob every time you save the document which could add up pretty quickly.`

I have no idea what this means. There's not a single line in the documentation on how to delete blobs, so I just assumed that couchbase deletes them if I don't include them anymore in the document.

**Comment by Rudiksz** [comment]
> The other major thing is that in order to properly delete the blob you should never just delete the property but instead you need to delete the data in the blob and pass it as an update. If you don't do this then the file will remain in the database and I don't think it would delete off the phone either.

I'm testing this right now, deleting only the blob keys leaves the files in the attachment folder, but compacting the database deletes the orphaned attachment files. That's pretty much in line with the expectations, as previous revisions still point to the deleted blobs, but after compaction they can be safely removed.

**Comment by bawelter** [comment]
> That's very confusing and counterintuitive. I already have to keep an extra copy of the id in my documents to be able to do a proper query, now I have to keep track of the revision and sequence manually too?
> 
> Having to do an extra read for **every** document I want to save, just to get the sequence number is a very bad design choice, and having queries that don't return id and revision are almost useless then.
> 
> Also I don't know if it's relevant or intended but the plugin code does not return the document revision even when doing a getDocument call. I was under the impression that updating a document requires an ID and the revision number.
> 
> `You will also want to check and make sure the attachments are properly deleted with the overwrite as a new document or you will have a duplicated attachment for the Blob every time you save the document which could add up pretty quickly.`
> 
> I have no idea what this means. There's not a single line in the documentation on how to delete blobs, so I just assumed that couchbase deletes them if I don't include them anymore in the document.

Please be a team player here, I am just trying to help and make sure you don't get any unexpected crashes.  I didn't design couchbase lite I just wrote a plugin to use it and if you have a better solution, I would invite you to contribute and work together with me to provide the solution.  I know it is frustrating when things don't work like you need them to but it's not like I get paid to do this, I do it in my free time.

**Comment by Rudiksz** [comment]
It wasn't a complained towards you, I was just trying to understand how couchbase is doing things becaue it's very confusing.

**Comment by Rudiksz** [comment]
I created a new pull request with a cleaner code and hopefully a more comprehensive fix.

**Pull request closed without merging**
