### PR TITLE
 Shreejadhav Array In and Group By Contributions

### PR DESCRIPTION
**Pull request by bawelter**

### CODE REVIEW

**Comment by bawelter** [comment]
There are issues with the alias expressions.  Probably just a misunderstanding of the JSON formatting and why each expression is in an array.  Will need to go through the code and fix this or maybe there is something I am not understanding.

**Comment by allanwolski** [comment]
I need it.
Do you have any plans to merge this?

**Comment by allanwolski** [comment]
Any updates?

**Comment by bawelter** [comment]
This was added in https://github.com/SaltechSystems/couchbase_lite/pull/93

**Pull request closed without merging**
